# Copyright 2017 neurodata (http://neurodata.io/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0 #
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

language: python
python:
  - "2.7"
sudo: required
dist:
  - trusty
  - xenial
notifications:
  email: false
install:
  - sudo apt-get sudo apt-get -o Dpkg::Options::="--force-confold" --force-yes -y upgrade
  - sudo apt-get update
  - sudo apt-get install python-dev
  - sudo apt-get install python-setuptools
  - sudo easy_install pip
  - pip install -r requirements.txt
  - make install
script:
- cd test && python test.py && cd -
group: edge
