language: python
python:
  - "2.7"
sudo: required
dist:
  - trusty
  - xenial
notifications:
  email: false
install:
  - pip install -r requirements.txt
  - make install
script:
- cd test && python test.py && cd -
group: edge
